# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PyNite Structural Analysis.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 688)
        MainWindow.setMinimumSize(QtCore.QSize(1278, 688))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabs.setObjectName("tabs")
        self.tab1Node = QtWidgets.QWidget()
        self.tab1Node.setObjectName("tab1Node")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab1Node)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame1defineNode = QtWidgets.QFrame(self.tab1Node)
        self.frame1defineNode.setMaximumSize(QtCore.QSize(480, 255))
        self.frame1defineNode.setObjectName("frame1defineNode")
        self._2 = QtWidgets.QGridLayout(self.frame1defineNode)
        self._2.setObjectName("_2")
        self.defineNodeLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeLabel.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.defineNodeLabel.setFont(font)
        self.defineNodeLabel.setObjectName("defineNodeLabel")
        self._2.addWidget(self.defineNodeLabel, 0, 0, 1, 1)
        self.informationTextNode = QtWidgets.QLabel(self.frame1defineNode)
        self.informationTextNode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.informationTextNode.setOpenExternalLinks(True)
        self.informationTextNode.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.informationTextNode.setObjectName("informationTextNode")
        self._2.addWidget(self.informationTextNode, 4, 0, 1, 1)
        self.defineNodeGrid = QtWidgets.QGridLayout()
        self.defineNodeGrid.setObjectName("defineNodeGrid")
        self.defineNodeZLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeZLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineNodeZLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineNodeZLabel.setObjectName("defineNodeZLabel")
        self.defineNodeGrid.addWidget(self.defineNodeZLabel, 3, 0, 1, 1)
        self.defineNodeZ = QtWidgets.QLineEdit(self.frame1defineNode)
        self.defineNodeZ.setMaximumSize(QtCore.QSize(400, 20))
        self.defineNodeZ.setObjectName("defineNodeZ")
        self.defineNodeGrid.addWidget(self.defineNodeZ, 3, 1, 1, 1)
        self.defineNodeY = QtWidgets.QLineEdit(self.frame1defineNode)
        self.defineNodeY.setMaximumSize(QtCore.QSize(400, 20))
        self.defineNodeY.setObjectName("defineNodeY")
        self.defineNodeGrid.addWidget(self.defineNodeY, 2, 1, 1, 1)
        self.defineNodeYLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeYLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineNodeYLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineNodeYLabel.setObjectName("defineNodeYLabel")
        self.defineNodeGrid.addWidget(self.defineNodeYLabel, 2, 0, 1, 1)
        self.defineNodeXLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeXLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineNodeXLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineNodeXLabel.setObjectName("defineNodeXLabel")
        self.defineNodeGrid.addWidget(self.defineNodeXLabel, 1, 0, 1, 1)
        self.defineNodeName = QtWidgets.QLineEdit(self.frame1defineNode)
        self.defineNodeName.setMaximumSize(QtCore.QSize(400, 20))
        self.defineNodeName.setObjectName("defineNodeName")
        self.defineNodeGrid.addWidget(self.defineNodeName, 0, 1, 1, 1)
        self.defineNodeX = QtWidgets.QLineEdit(self.frame1defineNode)
        self.defineNodeX.setMaximumSize(QtCore.QSize(400, 20))
        self.defineNodeX.setObjectName("defineNodeX")
        self.defineNodeGrid.addWidget(self.defineNodeX, 1, 1, 1, 1)
        self.defineNodeNameLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeNameLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineNodeNameLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineNodeNameLabel.setObjectName("defineNodeNameLabel")
        self.defineNodeGrid.addWidget(self.defineNodeNameLabel, 0, 0, 1, 1)
        self.defineNodeButton = QtWidgets.QPushButton(self.frame1defineNode)
        self.defineNodeButton.setAutoFillBackground(False)
        self.defineNodeButton.setCheckable(False)
        self.defineNodeButton.setObjectName("defineNodeButton")
        self.defineNodeGrid.addWidget(self.defineNodeButton, 4, 0, 1, 2)
        self._2.addLayout(self.defineNodeGrid, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame1defineNode, 0, 0, 1, 1)
        self.frame2updateNode = QtWidgets.QFrame(self.tab1Node)
        self.frame2updateNode.setMaximumSize(QtCore.QSize(16777215, 255))
        self.frame2updateNode.setObjectName("frame2updateNode")
        self.gridLayout = QtWidgets.QGridLayout(self.frame2updateNode)
        self.gridLayout.setObjectName("gridLayout")
        self.updateNodeHBox = QtWidgets.QHBoxLayout()
        self.updateNodeHBox.setObjectName("updateNodeHBox")
        self.updateNodeSA = QtWidgets.QScrollArea(self.frame2updateNode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeSA.sizePolicy().hasHeightForWidth())
        self.updateNodeSA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.updateNodeSA.setFont(font)
        self.updateNodeSA.setWidgetResizable(True)
        self.updateNodeSA.setObjectName("updateNodeSA")
        self.updateNodeSAW = QtWidgets.QWidget()
        self.updateNodeSAW.setGeometry(QtCore.QRect(0, 0, 728, 194))
        self.updateNodeSAW.setObjectName("updateNodeSAW")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.updateNodeSAW)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table2updateNode = QtWidgets.QGridLayout()
        self.table2updateNode.setObjectName("table2updateNode")
        self.updateNodeButton = QtWidgets.QPushButton(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeButton.sizePolicy().hasHeightForWidth())
        self.updateNodeButton.setSizePolicy(sizePolicy)
        self.updateNodeButton.setMinimumSize(QtCore.QSize(0, 23))
        self.updateNodeButton.setMaximumSize(QtCore.QSize(90, 23))
        self.updateNodeButton.setObjectName("updateNodeButton")
        self.table2updateNode.addWidget(self.updateNodeButton, 1, 4, 1, 1)
        self.deleteNodeButton = QtWidgets.QPushButton(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteNodeButton.sizePolicy().hasHeightForWidth())
        self.deleteNodeButton.setSizePolicy(sizePolicy)
        self.deleteNodeButton.setMinimumSize(QtCore.QSize(0, 23))
        self.deleteNodeButton.setMaximumSize(QtCore.QSize(90, 23))
        self.deleteNodeButton.setObjectName("deleteNodeButton")
        self.table2updateNode.addWidget(self.deleteNodeButton, 1, 5, 1, 1)
        self.updateNodeY = QtWidgets.QLineEdit(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeY.sizePolicy().hasHeightForWidth())
        self.updateNodeY.setSizePolicy(sizePolicy)
        self.updateNodeY.setMinimumSize(QtCore.QSize(10, 0))
        self.updateNodeY.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeY.setObjectName("updateNodeY")
        self.table2updateNode.addWidget(self.updateNodeY, 1, 2, 1, 1)
        self.updateNodeX = QtWidgets.QLineEdit(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeX.sizePolicy().hasHeightForWidth())
        self.updateNodeX.setSizePolicy(sizePolicy)
        self.updateNodeX.setMinimumSize(QtCore.QSize(10, 0))
        self.updateNodeX.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeX.setObjectName("updateNodeX")
        self.table2updateNode.addWidget(self.updateNodeX, 1, 1, 1, 1)
        self.updateNodeZ = QtWidgets.QLineEdit(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeZ.sizePolicy().hasHeightForWidth())
        self.updateNodeZ.setSizePolicy(sizePolicy)
        self.updateNodeZ.setMinimumSize(QtCore.QSize(10, 0))
        self.updateNodeZ.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeZ.setObjectName("updateNodeZ")
        self.table2updateNode.addWidget(self.updateNodeZ, 1, 3, 1, 1)
        self.updateNodeName = QtWidgets.QLineEdit(self.updateNodeSAW)
        self.updateNodeName.setMinimumSize(QtCore.QSize(150, 0))
        self.updateNodeName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeName.setObjectName("updateNodeName")
        self.table2updateNode.addWidget(self.updateNodeName, 1, 0, 1, 1)
        self.updateNodeNameLabel = QtWidgets.QLabel(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeNameLabel.sizePolicy().hasHeightForWidth())
        self.updateNodeNameLabel.setSizePolicy(sizePolicy)
        self.updateNodeNameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeNameLabel.setObjectName("updateNodeNameLabel")
        self.table2updateNode.addWidget(self.updateNodeNameLabel, 0, 0, 1, 1)
        self.updateNodeXLabel = QtWidgets.QLabel(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeXLabel.sizePolicy().hasHeightForWidth())
        self.updateNodeXLabel.setSizePolicy(sizePolicy)
        self.updateNodeXLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeXLabel.setObjectName("updateNodeXLabel")
        self.table2updateNode.addWidget(self.updateNodeXLabel, 0, 1, 1, 1)
        self.updateNodeYLabel = QtWidgets.QLabel(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeYLabel.sizePolicy().hasHeightForWidth())
        self.updateNodeYLabel.setSizePolicy(sizePolicy)
        self.updateNodeYLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeYLabel.setObjectName("updateNodeYLabel")
        self.table2updateNode.addWidget(self.updateNodeYLabel, 0, 2, 1, 1)
        self.updateNodeZLabel = QtWidgets.QLabel(self.updateNodeSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateNodeZLabel.sizePolicy().hasHeightForWidth())
        self.updateNodeZLabel.setSizePolicy(sizePolicy)
        self.updateNodeZLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateNodeZLabel.setObjectName("updateNodeZLabel")
        self.table2updateNode.addWidget(self.updateNodeZLabel, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.table2updateNode)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.updateNodeSA.setWidget(self.updateNodeSAW)
        self.updateNodeHBox.addWidget(self.updateNodeSA)
        self.gridLayout.addLayout(self.updateNodeHBox, 2, 0, 1, 1)
        self.updateNodeLabel = QtWidgets.QLabel(self.frame2updateNode)
        self.updateNodeLabel.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.updateNodeLabel.setFont(font)
        self.updateNodeLabel.setObjectName("updateNodeLabel")
        self.gridLayout.addWidget(self.updateNodeLabel, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame2updateNode, 0, 1, 1, 1)
        self.widget1plotAreaNode = QtWidgets.QWidget(self.tab1Node)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1plotAreaNode.sizePolicy().hasHeightForWidth())
        self.widget1plotAreaNode.setSizePolicy(sizePolicy)
        self.widget1plotAreaNode.setMinimumSize(QtCore.QSize(0, 300))
        self.widget1plotAreaNode.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.widget1plotAreaNode.setObjectName("widget1plotAreaNode")
        self.gridLayout_3.addWidget(self.widget1plotAreaNode, 1, 0, 1, 2)
        self.tabs.addTab(self.tab1Node, "")
        self.tab2Material = QtWidgets.QWidget()
        self.tab2Material.setObjectName("tab2Material")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab2Material)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame1defineMaterial = QtWidgets.QFrame(self.tab2Material)
        self.frame1defineMaterial.setMaximumSize(QtCore.QSize(480, 16777215))
        self.frame1defineMaterial.setObjectName("frame1defineMaterial")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame1defineMaterial)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.informationTextMaterial = QtWidgets.QLabel(self.frame1defineMaterial)
        self.informationTextMaterial.setMaximumSize(QtCore.QSize(16777215, 138))
        self.informationTextMaterial.setObjectName("informationTextMaterial")
        self.gridLayout_7.addWidget(self.informationTextMaterial, 2, 0, 1, 1)
        self.defineMaterialLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.defineMaterialLabel.setFont(font)
        self.defineMaterialLabel.setObjectName("defineMaterialLabel")
        self.gridLayout_7.addWidget(self.defineMaterialLabel, 0, 0, 1, 1)
        self.table1defineMaterial = QtWidgets.QGridLayout()
        self.table1defineMaterial.setObjectName("table1defineMaterial")
        self.defineMaterialIyLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialIyLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialIyLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialIyLabel.setObjectName("defineMaterialIyLabel")
        self.table1defineMaterial.addWidget(self.defineMaterialIyLabel, 4, 0, 1, 1)
        self.defineMaterialNameLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialNameLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialNameLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialNameLabel.setObjectName("defineMaterialNameLabel")
        self.table1defineMaterial.addWidget(self.defineMaterialNameLabel, 0, 0, 1, 1)
        self.defineMaterialIzLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialIzLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialIzLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialIzLabel.setObjectName("defineMaterialIzLabel")
        self.table1defineMaterial.addWidget(self.defineMaterialIzLabel, 5, 0, 1, 1)
        self.defineMaterialELabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialELabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialELabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialELabel.setObjectName("defineMaterialELabel")
        self.table1defineMaterial.addWidget(self.defineMaterialELabel, 1, 0, 1, 1)
        self.defineMaterialJLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialJLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialJLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialJLabel.setObjectName("defineMaterialJLabel")
        self.table1defineMaterial.addWidget(self.defineMaterialJLabel, 3, 0, 1, 1)
        self.defineMaterialALabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialALabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialALabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialALabel.setObjectName("defineMaterialALabel")
        self.table1defineMaterial.addWidget(self.defineMaterialALabel, 6, 0, 1, 1)
        self.defineMaterialGLabel = QtWidgets.QLabel(self.frame1defineMaterial)
        self.defineMaterialGLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMaterialGLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMaterialGLabel.setObjectName("defineMaterialGLabel")
        self.table1defineMaterial.addWidget(self.defineMaterialGLabel, 2, 0, 1, 1)
        self.defineMaterialE = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialE.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialE.setObjectName("defineMaterialE")
        self.table1defineMaterial.addWidget(self.defineMaterialE, 1, 1, 1, 1)
        self.defineMaterialButton = QtWidgets.QPushButton(self.frame1defineMaterial)
        self.defineMaterialButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.defineMaterialButton.setObjectName("defineMaterialButton")
        self.table1defineMaterial.addWidget(self.defineMaterialButton, 7, 0, 1, 2)
        self.defineMaterialName = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialName.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialName.setObjectName("defineMaterialName")
        self.table1defineMaterial.addWidget(self.defineMaterialName, 0, 1, 1, 1)
        self.defineMaterialG = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialG.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialG.setObjectName("defineMaterialG")
        self.table1defineMaterial.addWidget(self.defineMaterialG, 2, 1, 1, 1)
        self.defineMaterialJ = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialJ.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialJ.setObjectName("defineMaterialJ")
        self.table1defineMaterial.addWidget(self.defineMaterialJ, 3, 1, 1, 1)
        self.defineMaterialIy = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialIy.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialIy.setObjectName("defineMaterialIy")
        self.table1defineMaterial.addWidget(self.defineMaterialIy, 4, 1, 1, 1)
        self.defineMaterialA = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialA.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialA.setObjectName("defineMaterialA")
        self.table1defineMaterial.addWidget(self.defineMaterialA, 6, 1, 1, 1)
        self.defineMaterialIz = QtWidgets.QLineEdit(self.frame1defineMaterial)
        self.defineMaterialIz.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMaterialIz.setObjectName("defineMaterialIz")
        self.table1defineMaterial.addWidget(self.defineMaterialIz, 5, 1, 1, 1)
        self.gridLayout_7.addLayout(self.table1defineMaterial, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame1defineMaterial, 0, 0, 1, 1)
        self.frame2updateMaterial = QtWidgets.QFrame(self.tab2Material)
        self.frame2updateMaterial.setMinimumSize(QtCore.QSize(750, 0))
        self.frame2updateMaterial.setObjectName("frame2updateMaterial")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame2updateMaterial)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.updateMaterialLabel = QtWidgets.QLabel(self.frame2updateMaterial)
        self.updateMaterialLabel.setMaximumSize(QtCore.QSize(16777215, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.updateMaterialLabel.setFont(font)
        self.updateMaterialLabel.setObjectName("updateMaterialLabel")
        self.gridLayout_6.addWidget(self.updateMaterialLabel, 0, 0, 1, 1)
        self.updateMaterialHBox = QtWidgets.QHBoxLayout()
        self.updateMaterialHBox.setObjectName("updateMaterialHBox")
        self.updateMaterialSA = QtWidgets.QScrollArea(self.frame2updateMaterial)
        self.updateMaterialSA.setWidgetResizable(True)
        self.updateMaterialSA.setObjectName("updateMaterialSA")
        self.updateMaterialSAW = QtWidgets.QWidget()
        self.updateMaterialSAW.setGeometry(QtCore.QRect(0, 0, 692, 68))
        self.updateMaterialSAW.setObjectName("updateMaterialSAW")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.updateMaterialSAW)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table2updateMaterial = QtWidgets.QGridLayout()
        self.table2updateMaterial.setObjectName("table2updateMaterial")
        self.updateMaterialJLabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialJLabel.setObjectName("updateMaterialJLabel")
        self.table2updateMaterial.addWidget(self.updateMaterialJLabel, 0, 3, 1, 1)
        self.updateMaterialIyLabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialIyLabel.setObjectName("updateMaterialIyLabel")
        self.table2updateMaterial.addWidget(self.updateMaterialIyLabel, 0, 4, 1, 1)
        self.deleteMaterialButton = QtWidgets.QPushButton(self.updateMaterialSAW)
        self.deleteMaterialButton.setMinimumSize(QtCore.QSize(0, 23))
        self.deleteMaterialButton.setMaximumSize(QtCore.QSize(90, 23))
        self.deleteMaterialButton.setObjectName("deleteMaterialButton")
        self.table2updateMaterial.addWidget(self.deleteMaterialButton, 1, 8, 1, 1)
        self.updateMaterialGLabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialGLabel.setObjectName("updateMaterialGLabel")
        self.table2updateMaterial.addWidget(self.updateMaterialGLabel, 0, 2, 1, 1)
        self.updateMaterialNameLabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialNameLabel.setObjectName("updateMaterialNameLabel")
        self.table2updateMaterial.addWidget(self.updateMaterialNameLabel, 0, 0, 1, 1)
        self.updateMaterialButton = QtWidgets.QPushButton(self.updateMaterialSAW)
        self.updateMaterialButton.setMinimumSize(QtCore.QSize(0, 23))
        self.updateMaterialButton.setMaximumSize(QtCore.QSize(90, 23))
        self.updateMaterialButton.setObjectName("updateMaterialButton")
        self.table2updateMaterial.addWidget(self.updateMaterialButton, 1, 7, 1, 1)
        self.updateMaterialELabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialELabel.setObjectName("updateMaterialELabel")
        self.table2updateMaterial.addWidget(self.updateMaterialELabel, 0, 1, 1, 1)
        self.updateMaterialALabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialALabel.setObjectName("updateMaterialALabel")
        self.table2updateMaterial.addWidget(self.updateMaterialALabel, 0, 6, 1, 1)
        self.updateMaterialIzLabel = QtWidgets.QLabel(self.updateMaterialSAW)
        self.updateMaterialIzLabel.setObjectName("updateMaterialIzLabel")
        self.table2updateMaterial.addWidget(self.updateMaterialIzLabel, 0, 5, 1, 1)
        self.updateMaterialName = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialName.setMinimumSize(QtCore.QSize(150, 0))
        self.updateMaterialName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateMaterialName.setObjectName("updateMaterialName")
        self.table2updateMaterial.addWidget(self.updateMaterialName, 1, 0, 1, 1)
        self.updateMaterialE = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialE.setObjectName("updateMaterialE")
        self.table2updateMaterial.addWidget(self.updateMaterialE, 1, 1, 1, 1)
        self.updateMaterialG = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialG.setObjectName("updateMaterialG")
        self.table2updateMaterial.addWidget(self.updateMaterialG, 1, 2, 1, 1)
        self.updateMaterialJ = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialJ.setObjectName("updateMaterialJ")
        self.table2updateMaterial.addWidget(self.updateMaterialJ, 1, 3, 1, 1)
        self.updateMaterialIy = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialIy.setObjectName("updateMaterialIy")
        self.table2updateMaterial.addWidget(self.updateMaterialIy, 1, 4, 1, 1)
        self.updateMaterialIz = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialIz.setObjectName("updateMaterialIz")
        self.table2updateMaterial.addWidget(self.updateMaterialIz, 1, 5, 1, 1)
        self.updateMaterialA = QtWidgets.QLineEdit(self.updateMaterialSAW)
        self.updateMaterialA.setObjectName("updateMaterialA")
        self.table2updateMaterial.addWidget(self.updateMaterialA, 1, 6, 1, 1)
        self.verticalLayout_3.addLayout(self.table2updateMaterial)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.updateMaterialSA.setWidget(self.updateMaterialSAW)
        self.updateMaterialHBox.addWidget(self.updateMaterialSA)
        self.gridLayout_6.addLayout(self.updateMaterialHBox, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame2updateMaterial, 0, 3, 1, 1)
        self.tabs.addTab(self.tab2Material, "")
        self.tab3Member = QtWidgets.QWidget()
        self.tab3Member.setObjectName("tab3Member")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab3Member)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget1plotAreaMember = QtWidgets.QWidget(self.tab3Member)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1plotAreaMember.sizePolicy().hasHeightForWidth())
        self.widget1plotAreaMember.setSizePolicy(sizePolicy)
        self.widget1plotAreaMember.setMinimumSize(QtCore.QSize(0, 300))
        self.widget1plotAreaMember.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setKerning(True)
        self.widget1plotAreaMember.setFont(font)
        self.widget1plotAreaMember.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget1plotAreaMember.setObjectName("widget1plotAreaMember")
        self.gridLayout_5.addWidget(self.widget1plotAreaMember, 1, 0, 1, 2)
        self.frame1defineMember = QtWidgets.QFrame(self.tab3Member)
        self.frame1defineMember.setMinimumSize(QtCore.QSize(480, 0))
        self.frame1defineMember.setMaximumSize(QtCore.QSize(480, 255))
        self.frame1defineMember.setObjectName("frame1defineMember")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame1defineMember)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.table1defineMember = QtWidgets.QGridLayout()
        self.table1defineMember.setObjectName("table1defineMember")
        self.defineMemberINode = QtWidgets.QComboBox(self.frame1defineMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineMemberINode.sizePolicy().hasHeightForWidth())
        self.defineMemberINode.setSizePolicy(sizePolicy)
        self.defineMemberINode.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMemberINode.setObjectName("defineMemberINode")
        self.table1defineMember.addWidget(self.defineMemberINode, 1, 1, 1, 1)
        self.defineMemberNameLabel = QtWidgets.QLabel(self.frame1defineMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineMemberNameLabel.sizePolicy().hasHeightForWidth())
        self.defineMemberNameLabel.setSizePolicy(sizePolicy)
        self.defineMemberNameLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMemberNameLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMemberNameLabel.setObjectName("defineMemberNameLabel")
        self.table1defineMember.addWidget(self.defineMemberNameLabel, 0, 0, 1, 1)
        self.defineMemberMaterial = QtWidgets.QComboBox(self.frame1defineMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineMemberMaterial.sizePolicy().hasHeightForWidth())
        self.defineMemberMaterial.setSizePolicy(sizePolicy)
        self.defineMemberMaterial.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMemberMaterial.setObjectName("defineMemberMaterial")
        self.table1defineMember.addWidget(self.defineMemberMaterial, 3, 1, 1, 1)
        self.defineMemberMaterialLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberMaterialLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMemberMaterialLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMemberMaterialLabel.setObjectName("defineMemberMaterialLabel")
        self.table1defineMember.addWidget(self.defineMemberMaterialLabel, 3, 0, 1, 1)
        self.defineMemberJNodeLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberJNodeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMemberJNodeLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMemberJNodeLabel.setObjectName("defineMemberJNodeLabel")
        self.table1defineMember.addWidget(self.defineMemberJNodeLabel, 2, 0, 1, 1)
        self.defineMemberINodeLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberINodeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.defineMemberINodeLabel.setMaximumSize(QtCore.QSize(80, 20))
        self.defineMemberINodeLabel.setObjectName("defineMemberINodeLabel")
        self.table1defineMember.addWidget(self.defineMemberINodeLabel, 1, 0, 1, 1)
        self.defineMemberName = QtWidgets.QLineEdit(self.frame1defineMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineMemberName.sizePolicy().hasHeightForWidth())
        self.defineMemberName.setSizePolicy(sizePolicy)
        self.defineMemberName.setMinimumSize(QtCore.QSize(100, 0))
        self.defineMemberName.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMemberName.setObjectName("defineMemberName")
        self.table1defineMember.addWidget(self.defineMemberName, 0, 1, 1, 1)
        self.defineMemberJNode = QtWidgets.QComboBox(self.frame1defineMember)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defineMemberJNode.sizePolicy().hasHeightForWidth())
        self.defineMemberJNode.setSizePolicy(sizePolicy)
        self.defineMemberJNode.setMaximumSize(QtCore.QSize(400, 20))
        self.defineMemberJNode.setObjectName("defineMemberJNode")
        self.table1defineMember.addWidget(self.defineMemberJNode, 2, 1, 1, 1)
        self.defineMemberButton = QtWidgets.QPushButton(self.frame1defineMember)
        self.defineMemberButton.setMaximumSize(QtCore.QSize(16777215, 23))
        self.defineMemberButton.setObjectName("defineMemberButton")
        self.table1defineMember.addWidget(self.defineMemberButton, 4, 0, 1, 2)
        self.gridLayout_10.addLayout(self.table1defineMember, 1, 0, 1, 1)
        self.defineMemberLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberLabel.setMaximumSize(QtCore.QSize(1500, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.defineMemberLabel.setFont(font)
        self.defineMemberLabel.setObjectName("defineMemberLabel")
        self.gridLayout_10.addWidget(self.defineMemberLabel, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame1defineMember, 0, 0, 1, 1)
        self.frame2updateMember = QtWidgets.QFrame(self.tab3Member)
        self.frame2updateMember.setMaximumSize(QtCore.QSize(16777215, 255))
        self.frame2updateMember.setObjectName("frame2updateMember")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame2updateMember)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.updateMemberLabel = QtWidgets.QLabel(self.frame2updateMember)
        self.updateMemberLabel.setMaximumSize(QtCore.QSize(1500, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.updateMemberLabel.setFont(font)
        self.updateMemberLabel.setObjectName("updateMemberLabel")
        self.gridLayout_2.addWidget(self.updateMemberLabel, 0, 0, 1, 1)
        self.updateMemberHBox = QtWidgets.QHBoxLayout()
        self.updateMemberHBox.setObjectName("updateMemberHBox")
        self.updateMemberSA = QtWidgets.QScrollArea(self.frame2updateMember)
        self.updateMemberSA.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.updateMemberSA.setWidgetResizable(True)
        self.updateMemberSA.setObjectName("updateMemberSA")
        self.updateMemberSAW = QtWidgets.QWidget()
        self.updateMemberSAW.setGeometry(QtCore.QRect(0, 0, 728, 194))
        self.updateMemberSAW.setObjectName("updateMemberSAW")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.updateMemberSAW)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table2updateMember = QtWidgets.QGridLayout()
        self.table2updateMember.setObjectName("table2updateMember")
        self.updateMemberINode = QtWidgets.QComboBox(self.updateMemberSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateMemberINode.sizePolicy().hasHeightForWidth())
        self.updateMemberINode.setSizePolicy(sizePolicy)
        self.updateMemberINode.setObjectName("updateMemberINode")
        self.table2updateMember.addWidget(self.updateMemberINode, 1, 1, 1, 1)
        self.updateMemberNameLabel = QtWidgets.QLabel(self.updateMemberSAW)
        self.updateMemberNameLabel.setObjectName("updateMemberNameLabel")
        self.table2updateMember.addWidget(self.updateMemberNameLabel, 0, 0, 1, 1)
        self.updateMemberINodeLabel = QtWidgets.QLabel(self.updateMemberSAW)
        self.updateMemberINodeLabel.setObjectName("updateMemberINodeLabel")
        self.table2updateMember.addWidget(self.updateMemberINodeLabel, 0, 1, 1, 1)
        self.updateMemberJNode = QtWidgets.QComboBox(self.updateMemberSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateMemberJNode.sizePolicy().hasHeightForWidth())
        self.updateMemberJNode.setSizePolicy(sizePolicy)
        self.updateMemberJNode.setObjectName("updateMemberJNode")
        self.table2updateMember.addWidget(self.updateMemberJNode, 1, 2, 1, 1)
        self.updateMemberName = QtWidgets.QLineEdit(self.updateMemberSAW)
        self.updateMemberName.setMinimumSize(QtCore.QSize(150, 0))
        self.updateMemberName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.updateMemberName.setFrame(True)
        self.updateMemberName.setObjectName("updateMemberName")
        self.table2updateMember.addWidget(self.updateMemberName, 1, 0, 1, 1)
        self.updateMemberJNodeLabel = QtWidgets.QLabel(self.updateMemberSAW)
        self.updateMemberJNodeLabel.setObjectName("updateMemberJNodeLabel")
        self.table2updateMember.addWidget(self.updateMemberJNodeLabel, 0, 2, 1, 1)
        self.updateMemberMaterial = QtWidgets.QComboBox(self.updateMemberSAW)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateMemberMaterial.sizePolicy().hasHeightForWidth())
        self.updateMemberMaterial.setSizePolicy(sizePolicy)
        self.updateMemberMaterial.setObjectName("updateMemberMaterial")
        self.table2updateMember.addWidget(self.updateMemberMaterial, 1, 3, 1, 1)
        self.updateMemberButton = QtWidgets.QPushButton(self.updateMemberSAW)
        self.updateMemberButton.setMinimumSize(QtCore.QSize(0, 23))
        self.updateMemberButton.setMaximumSize(QtCore.QSize(90, 23))
        self.updateMemberButton.setObjectName("updateMemberButton")
        self.table2updateMember.addWidget(self.updateMemberButton, 1, 4, 1, 1)
        self.updateMemberMaterialLabel = QtWidgets.QLabel(self.updateMemberSAW)
        self.updateMemberMaterialLabel.setObjectName("updateMemberMaterialLabel")
        self.table2updateMember.addWidget(self.updateMemberMaterialLabel, 0, 3, 1, 1)
        self.deleteMemberButton = QtWidgets.QPushButton(self.updateMemberSAW)
        self.deleteMemberButton.setMinimumSize(QtCore.QSize(0, 23))
        self.deleteMemberButton.setMaximumSize(QtCore.QSize(90, 23))
        self.deleteMemberButton.setObjectName("deleteMemberButton")
        self.table2updateMember.addWidget(self.deleteMemberButton, 1, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.table2updateMember)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.updateMemberSA.setWidget(self.updateMemberSAW)
        self.updateMemberHBox.addWidget(self.updateMemberSA)
        self.gridLayout_2.addLayout(self.updateMemberHBox, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame2updateMember, 0, 1, 1, 1)
        self.tabs.addTab(self.tab3Member, "")
        self.horizontalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.defineNodeName, self.defineNodeX)
        MainWindow.setTabOrder(self.defineNodeX, self.defineNodeY)
        MainWindow.setTabOrder(self.defineNodeY, self.defineNodeZ)
        MainWindow.setTabOrder(self.defineNodeZ, self.defineNodeButton)
        MainWindow.setTabOrder(self.defineNodeButton, self.updateNodeSA)
        MainWindow.setTabOrder(self.updateNodeSA, self.updateNodeName)
        MainWindow.setTabOrder(self.updateNodeName, self.updateNodeX)
        MainWindow.setTabOrder(self.updateNodeX, self.updateNodeY)
        MainWindow.setTabOrder(self.updateNodeY, self.updateNodeZ)
        MainWindow.setTabOrder(self.updateNodeZ, self.updateNodeButton)
        MainWindow.setTabOrder(self.updateNodeButton, self.deleteNodeButton)
        MainWindow.setTabOrder(self.deleteNodeButton, self.defineMaterialName)
        MainWindow.setTabOrder(self.defineMaterialName, self.defineMaterialE)
        MainWindow.setTabOrder(self.defineMaterialE, self.defineMaterialG)
        MainWindow.setTabOrder(self.defineMaterialG, self.defineMaterialJ)
        MainWindow.setTabOrder(self.defineMaterialJ, self.defineMaterialIy)
        MainWindow.setTabOrder(self.defineMaterialIy, self.defineMaterialIz)
        MainWindow.setTabOrder(self.defineMaterialIz, self.defineMaterialA)
        MainWindow.setTabOrder(self.defineMaterialA, self.defineMaterialButton)
        MainWindow.setTabOrder(self.defineMaterialButton, self.updateMaterialSA)
        MainWindow.setTabOrder(self.updateMaterialSA, self.updateMaterialName)
        MainWindow.setTabOrder(self.updateMaterialName, self.updateMaterialE)
        MainWindow.setTabOrder(self.updateMaterialE, self.updateMaterialG)
        MainWindow.setTabOrder(self.updateMaterialG, self.updateMaterialJ)
        MainWindow.setTabOrder(self.updateMaterialJ, self.updateMaterialIy)
        MainWindow.setTabOrder(self.updateMaterialIy, self.updateMaterialIz)
        MainWindow.setTabOrder(self.updateMaterialIz, self.updateMaterialA)
        MainWindow.setTabOrder(self.updateMaterialA, self.updateMaterialButton)
        MainWindow.setTabOrder(self.updateMaterialButton, self.deleteMaterialButton)
        MainWindow.setTabOrder(self.deleteMaterialButton, self.defineMemberName)
        MainWindow.setTabOrder(self.defineMemberName, self.defineMemberINode)
        MainWindow.setTabOrder(self.defineMemberINode, self.defineMemberJNode)
        MainWindow.setTabOrder(self.defineMemberJNode, self.defineMemberMaterial)
        MainWindow.setTabOrder(self.defineMemberMaterial, self.defineMemberButton)
        MainWindow.setTabOrder(self.defineMemberButton, self.updateMemberSA)
        MainWindow.setTabOrder(self.updateMemberSA, self.updateMemberName)
        MainWindow.setTabOrder(self.updateMemberName, self.updateMemberINode)
        MainWindow.setTabOrder(self.updateMemberINode, self.updateMemberJNode)
        MainWindow.setTabOrder(self.updateMemberJNode, self.updateMemberMaterial)
        MainWindow.setTabOrder(self.updateMemberMaterial, self.updateMemberButton)
        MainWindow.setTabOrder(self.updateMemberButton, self.deleteMemberButton)
        MainWindow.setTabOrder(self.deleteMemberButton, self.tabs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.defineNodeLabel.setText(_translate("MainWindow", "Define Nodes"))
        self.informationTextNode.setText(_translate("MainWindow", "<html><head/><body><p>Use * for multiplication and ** for exponentials.</p><p>Angles are in radians.</p><p>Visit <a href=\"https://docs.sympy.org/latest/modules/functions/elementary.html\"><span style=\" text-decoration: underline; color:#000000;\">SymPy Elementary Functions</span></a> for a list of mathematical functions.</p></body></html>"))
        self.defineNodeZLabel.setText(_translate("MainWindow", "Global z (m)"))
        self.defineNodeYLabel.setText(_translate("MainWindow", "Global y (m)"))
        self.defineNodeXLabel.setText(_translate("MainWindow", "Global x (m)"))
        self.defineNodeNameLabel.setText(_translate("MainWindow", "Name"))
        self.defineNodeButton.setText(_translate("MainWindow", "Add Node"))
        self.updateNodeButton.setText(_translate("MainWindow", "Update"))
        self.deleteNodeButton.setText(_translate("MainWindow", "Delete"))
        self.updateNodeName.setText(_translate("MainWindow", "Add node to get started"))
        self.updateNodeNameLabel.setText(_translate("MainWindow", "Name"))
        self.updateNodeXLabel.setText(_translate("MainWindow", "Global x (m)"))
        self.updateNodeYLabel.setText(_translate("MainWindow", "Global y (m)"))
        self.updateNodeZLabel.setText(_translate("MainWindow", "Global z (m)"))
        self.updateNodeLabel.setText(_translate("MainWindow", "Nodes"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1Node), _translate("MainWindow", "Nodes"))
        self.informationTextMaterial.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">E - Young\'s Modulus </p><p align=\"right\">G - Shear Modulus </p><p align=\"right\">Ix/J - Polar Moment of Inertia </p><p align=\"right\">Iy - Moment of Inertia in y-direction</p><p align=\"right\">Iz - Moment of Inertia in z-direction</p><p align=\"right\">A - Cross-sectional Area</p></body></html>"))
        self.defineMaterialLabel.setText(_translate("MainWindow", "Define Materials"))
        self.defineMaterialIyLabel.setText(_translate("MainWindow", "<html><head/><body><p>Iy (kg m<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.defineMaterialNameLabel.setText(_translate("MainWindow", "Name"))
        self.defineMaterialIzLabel.setText(_translate("MainWindow", "<html><head/><body><p>Iz (kg m<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.defineMaterialELabel.setText(_translate("MainWindow", "E (Pa)"))
        self.defineMaterialJLabel.setText(_translate("MainWindow", "<html><head/><body><p>Ix/J (kg m<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.defineMaterialALabel.setText(_translate("MainWindow", "<html><head/><body><p>A (m<span style=\" vertical-align:super;\">2</span>)</p></body></html>"))
        self.defineMaterialGLabel.setText(_translate("MainWindow", "G (Pa)"))
        self.defineMaterialButton.setText(_translate("MainWindow", "Add Material"))
        self.updateMaterialLabel.setText(_translate("MainWindow", "Materials"))
        self.updateMaterialJLabel.setText(_translate("MainWindow", "Ix/J"))
        self.updateMaterialIyLabel.setText(_translate("MainWindow", "Iy"))
        self.deleteMaterialButton.setText(_translate("MainWindow", "Delete"))
        self.updateMaterialGLabel.setText(_translate("MainWindow", "G"))
        self.updateMaterialNameLabel.setText(_translate("MainWindow", "Name"))
        self.updateMaterialButton.setText(_translate("MainWindow", "Update"))
        self.updateMaterialELabel.setText(_translate("MainWindow", "E"))
        self.updateMaterialALabel.setText(_translate("MainWindow", "A"))
        self.updateMaterialIzLabel.setText(_translate("MainWindow", "Iz"))
        self.updateMaterialName.setText(_translate("MainWindow", "Add Material to get started"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2Material), _translate("MainWindow", "Materials"))
        self.defineMemberNameLabel.setText(_translate("MainWindow", "Name"))
        self.defineMemberMaterialLabel.setText(_translate("MainWindow", "Material ID"))
        self.defineMemberJNodeLabel.setText(_translate("MainWindow", "Node J"))
        self.defineMemberINodeLabel.setText(_translate("MainWindow", "Node I"))
        self.defineMemberButton.setText(_translate("MainWindow", "Add Member"))
        self.defineMemberLabel.setText(_translate("MainWindow", "Define Members"))
        self.updateMemberLabel.setText(_translate("MainWindow", "Members"))
        self.updateMemberNameLabel.setText(_translate("MainWindow", "Name"))
        self.updateMemberINodeLabel.setText(_translate("MainWindow", "Node I"))
        self.updateMemberName.setText(_translate("MainWindow", "Add Member to get started"))
        self.updateMemberJNodeLabel.setText(_translate("MainWindow", "Node J"))
        self.updateMemberButton.setText(_translate("MainWindow", "Update"))
        self.updateMemberMaterialLabel.setText(_translate("MainWindow", "Material ID"))
        self.deleteMemberButton.setText(_translate("MainWindow", "Delete"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab3Member), _translate("MainWindow", "Members"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
