# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PyNite Structural Analysis.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1278, 688))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setMinimumSize(QtCore.QSize(1200, 600))
        self.tabs.setObjectName("tabs")
        self.tab1Node = QtWidgets.QWidget()
        self.tab1Node.setObjectName("tab1Node")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab1Node)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame1defineNode = QtWidgets.QFrame(self.tab1Node)
        self.frame1defineNode.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame1defineNode.setAutoFillBackground(True)
        self.frame1defineNode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1defineNode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1defineNode.setObjectName("frame1defineNode")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame1defineNode)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.table1defineNode = QtWidgets.QGridLayout()
        self.table1defineNode.setObjectName("table1defineNode")
        self.defineNodeNameLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeNameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.defineNodeNameLabel.setObjectName("defineNodeNameLabel")
        self.table1defineNode.addWidget(self.defineNodeNameLabel, 0, 0, 1, 1)
        self.defineNodeName = QtWidgets.QLineEdit(self.frame1defineNode)
        self.defineNodeName.setMinimumSize(QtCore.QSize(200, 0))
        self.defineNodeName.setMaximumSize(QtCore.QSize(400, 16777215))
        self.defineNodeName.setObjectName("defineNodeName")
        self.table1defineNode.addWidget(self.defineNodeName, 1, 0, 1, 1)
        self.defineNodeZLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeZLabel.setObjectName("defineNodeZLabel")
        self.table1defineNode.addWidget(self.defineNodeZLabel, 0, 3, 1, 1)
        self.defineZnode = QtWidgets.QLineEdit(self.frame1defineNode)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.defineZnode.sizePolicy().hasHeightForWidth())
        self.defineZnode.setSizePolicy(sizePolicy)
        self.defineZnode.setMinimumSize(QtCore.QSize(10, 0))
        self.defineZnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.defineZnode.setObjectName("defineZnode")
        self.table1defineNode.addWidget(self.defineZnode, 1, 3, 1, 1)
        self.defineNodeYLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeYLabel.setObjectName("defineNodeYLabel")
        self.table1defineNode.addWidget(self.defineNodeYLabel, 0, 2, 1, 1)
        self.defineNodeXLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeXLabel.setObjectName("defineNodeXLabel")
        self.table1defineNode.addWidget(self.defineNodeXLabel, 0, 1, 1, 1)
        self.defineXnode = QtWidgets.QLineEdit(self.frame1defineNode)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.defineXnode.sizePolicy().hasHeightForWidth())
        self.defineXnode.setSizePolicy(sizePolicy)
        self.defineXnode.setMinimumSize(QtCore.QSize(10, 0))
        self.defineXnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.defineXnode.setObjectName("defineXnode")
        self.table1defineNode.addWidget(self.defineXnode, 1, 1, 1, 1)
        self.defineYnode = QtWidgets.QLineEdit(self.frame1defineNode)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.defineYnode.sizePolicy().hasHeightForWidth())
        self.defineYnode.setSizePolicy(sizePolicy)
        self.defineYnode.setMinimumSize(QtCore.QSize(10, 0))
        self.defineYnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.defineYnode.setObjectName("defineYnode")
        self.table1defineNode.addWidget(self.defineYnode, 1, 2, 1, 1)
        self.addNodeButton = QtWidgets.QPushButton(self.frame1defineNode)
        self.addNodeButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.addNodeButton.setAutoFillBackground(False)
        self.addNodeButton.setCheckable(False)
        self.addNodeButton.setAutoDefault(False)
        self.addNodeButton.setDefault(False)
        self.addNodeButton.setFlat(False)
        self.addNodeButton.setObjectName("addNodeButton")
        self.table1defineNode.addWidget(self.addNodeButton, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.frame1defineNode)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing
                                | QtCore.Qt.AlignVCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse
                                           | QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.table1defineNode.addWidget(self.label, 2, 0, 1, 5)
        self.gridLayout_9.addLayout(self.table1defineNode, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 2, 0, 1, 1)
        self.defineNodeLabel = QtWidgets.QLabel(self.frame1defineNode)
        self.defineNodeLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.defineNodeLabel.setFont(font)
        self.defineNodeLabel.setObjectName("defineNodeLabel")
        self.gridLayout_9.addWidget(self.defineNodeLabel, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame1defineNode, 0, 0, 1, 1)
        self.frame2editNode = QtWidgets.QFrame(self.tab1Node)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame2editNode.sizePolicy().hasHeightForWidth())
        self.frame2editNode.setSizePolicy(sizePolicy)
        self.frame2editNode.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame2editNode.setAutoFillBackground(True)
        self.frame2editNode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2editNode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2editNode.setObjectName("frame2editNode")
        self.gridLayout = QtWidgets.QGridLayout(self.frame2editNode)
        self.gridLayout.setObjectName("gridLayout")
        self.editNodeLabel = QtWidgets.QLabel(self.frame2editNode)
        self.editNodeLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.editNodeLabel.setFont(font)
        self.editNodeLabel.setObjectName("editNodeLabel")
        self.gridLayout.addWidget(self.editNodeLabel, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame2editNode)
        font = QtGui.QFont()
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 585, 268))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table2editNode = QtWidgets.QGridLayout()
        self.table2editNode.setObjectName("table2editNode")
        self.editNodeName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.editNodeName.setMinimumSize(QtCore.QSize(200, 0))
        self.editNodeName.setMaximumSize(QtCore.QSize(400, 16777215))
        self.editNodeName.setObjectName("editNodeName")
        self.table2editNode.addWidget(self.editNodeName, 0, 0, 1, 1)
        self.updateNodeButton = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.updateNodeButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.updateNodeButton.setObjectName("updateNodeButton")
        self.table2editNode.addWidget(self.updateNodeButton, 0, 4, 1, 1)
        self.editZnode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.editZnode.sizePolicy().hasHeightForWidth())
        self.editZnode.setSizePolicy(sizePolicy)
        self.editZnode.setMinimumSize(QtCore.QSize(10, 0))
        self.editZnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.editZnode.setObjectName("editZnode")
        self.table2editNode.addWidget(self.editZnode, 0, 3, 1, 1)
        self.deleteNodeButton = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.deleteNodeButton.setObjectName("deleteNodeButton")
        self.table2editNode.addWidget(self.deleteNodeButton, 0, 5, 1, 1)
        self.editXnode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.editXnode.sizePolicy().hasHeightForWidth())
        self.editXnode.setSizePolicy(sizePolicy)
        self.editXnode.setMinimumSize(QtCore.QSize(10, 0))
        self.editXnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.editXnode.setObjectName("editXnode")
        self.table2editNode.addWidget(self.editXnode, 0, 1, 1, 1)
        self.editYnode = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.editYnode.sizePolicy().hasHeightForWidth())
        self.editYnode.setSizePolicy(sizePolicy)
        self.editYnode.setMinimumSize(QtCore.QSize(10, 0))
        self.editYnode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.editYnode.setObjectName("editYnode")
        self.table2editNode.addWidget(self.editYnode, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.table2editNode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame2editNode, 0, 1, 1, 1)
        self.widget1plotAreaNode = QtWidgets.QWidget(self.tab1Node)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget1plotAreaNode.sizePolicy().hasHeightForWidth())
        self.widget1plotAreaNode.setSizePolicy(sizePolicy)
        self.widget1plotAreaNode.setMinimumSize(QtCore.QSize(0, 300))
        self.widget1plotAreaNode.setMaximumSize(QtCore.QSize(16777215, 640))
        self.widget1plotAreaNode.setObjectName("widget1plotAreaNode")
        self.gridLayout_3.addWidget(self.widget1plotAreaNode, 1, 0, 1, 2)
        self.tabs.addTab(self.tab1Node, "")
        self.tab2Member = QtWidgets.QWidget()
        self.tab2Member.setObjectName("tab2Member")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab2Member)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame2editMember = QtWidgets.QFrame(self.tab2Member)
        self.frame2editMember.setAutoFillBackground(True)
        self.frame2editMember.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2editMember.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2editMember.setObjectName("frame2editMember")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame2editMember)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.editMemberLabel = QtWidgets.QLabel(self.frame2editMember)
        self.editMemberLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.editMemberLabel.setFont(font)
        self.editMemberLabel.setObjectName("editMemberLabel")
        self.gridLayout_2.addWidget(self.editMemberLabel, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame2editMember)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 591, 268))
        self.scrollAreaWidgetContents_2.setObjectName(
            "scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.table2editMember = QtWidgets.QGridLayout()
        self.table2editMember.setObjectName("table2editMember")
        self.updateMemberButton = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_2)
        self.updateMemberButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.updateMemberButton.setObjectName("updateMemberButton")
        self.table2editMember.addWidget(self.updateMemberButton, 0, 3, 1, 1)
        self.editNodeJ = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.editNodeJ.setObjectName("editNodeJ")
        self.table2editMember.addWidget(self.editNodeJ, 0, 2, 1, 1)
        self.editNodeI = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.editNodeI.setObjectName("editNodeI")
        self.table2editMember.addWidget(self.editNodeI, 0, 1, 1, 1)
        self.editMemberName = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents_2)
        self.editMemberName.setMinimumSize(QtCore.QSize(200, 0))
        self.editMemberName.setMaximumSize(QtCore.QSize(400, 16777215))
        self.editMemberName.setObjectName("editMemberName")
        self.table2editMember.addWidget(self.editMemberName, 0, 0, 1, 1)
        self.deleteMemberButton = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents_2)
        self.deleteMemberButton.setObjectName("deleteMemberButton")
        self.table2editMember.addWidget(self.deleteMemberButton, 0, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.table2editMember)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.scrollArea_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame2editMember, 0, 1, 1, 1)
        self.frame1defineMember = QtWidgets.QFrame(self.tab2Member)
        self.frame1defineMember.setAutoFillBackground(True)
        self.frame1defineMember.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1defineMember.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1defineMember.setObjectName("frame1defineMember")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame1defineMember)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.table1defineMember = QtWidgets.QGridLayout()
        self.table1defineMember.setObjectName("table1defineMember")
        self.defineMemberNameLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberNameLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.defineMemberNameLabel.setObjectName("defineMemberNameLabel")
        self.table1defineMember.addWidget(self.defineMemberNameLabel, 0, 0, 1,
                                          1)
        self.defineNodeJLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineNodeJLabel.setObjectName("defineNodeJLabel")
        self.table1defineMember.addWidget(self.defineNodeJLabel, 0, 2, 1, 1)
        self.addMemberButton = QtWidgets.QPushButton(self.frame1defineMember)
        self.addMemberButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.addMemberButton.setObjectName("addMemberButton")
        self.table1defineMember.addWidget(self.addMemberButton, 1, 3, 1, 1)
        self.defineMemberName = QtWidgets.QLineEdit(self.frame1defineMember)
        self.defineMemberName.setMinimumSize(QtCore.QSize(200, 0))
        self.defineMemberName.setMaximumSize(QtCore.QSize(400, 16777215))
        self.defineMemberName.setObjectName("defineMemberName")
        self.table1defineMember.addWidget(self.defineMemberName, 1, 0, 1, 1)
        self.defineNodeILabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineNodeILabel.setObjectName("defineNodeILabel")
        self.table1defineMember.addWidget(self.defineNodeILabel, 0, 1, 1, 1)
        self.defineNodeI = QtWidgets.QComboBox(self.frame1defineMember)
        self.defineNodeI.setObjectName("defineNodeI")
        self.table1defineMember.addWidget(self.defineNodeI, 1, 1, 1, 1)
        self.defineNodeJ = QtWidgets.QComboBox(self.frame1defineMember)
        self.defineNodeJ.setObjectName("defineNodeJ")
        self.table1defineMember.addWidget(self.defineNodeJ, 1, 2, 1, 1)
        self.gridLayout_10.addLayout(self.table1defineMember, 1, 0, 1, 1)
        self.defineMemberLabel = QtWidgets.QLabel(self.frame1defineMember)
        self.defineMemberLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.defineMemberLabel.setFont(font)
        self.defineMemberLabel.setObjectName("defineMemberLabel")
        self.gridLayout_10.addWidget(self.defineMemberLabel, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame1defineMember, 0, 0, 1, 1)
        self.widget1PlotAreaMember = QtWidgets.QWidget(self.tab2Member)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.widget1PlotAreaMember.sizePolicy().hasHeightForWidth())
        self.widget1PlotAreaMember.setSizePolicy(sizePolicy)
        self.widget1PlotAreaMember.setMinimumSize(QtCore.QSize(0, 300))
        self.widget1PlotAreaMember.setMaximumSize(QtCore.QSize(16777215, 640))
        font = QtGui.QFont()
        font.setKerning(True)
        self.widget1PlotAreaMember.setFont(font)
        self.widget1PlotAreaMember.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget1PlotAreaMember.setObjectName("widget1PlotAreaMember")
        self.gridLayout_5.addWidget(self.widget1PlotAreaMember, 1, 0, 1, 2)
        self.tabs.addTab(self.tab2Member, "")
        self.horizontalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.defineNodeName, self.defineXnode)
        MainWindow.setTabOrder(self.defineXnode, self.defineYnode)
        MainWindow.setTabOrder(self.defineYnode, self.defineZnode)
        MainWindow.setTabOrder(self.defineZnode, self.addNodeButton)
        MainWindow.setTabOrder(self.addNodeButton, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.editNodeName)
        MainWindow.setTabOrder(self.editNodeName, self.editXnode)
        MainWindow.setTabOrder(self.editXnode, self.editYnode)
        MainWindow.setTabOrder(self.editYnode, self.editZnode)
        MainWindow.setTabOrder(self.editZnode, self.updateNodeButton)
        MainWindow.setTabOrder(self.updateNodeButton, self.deleteNodeButton)
        MainWindow.setTabOrder(self.deleteNodeButton, self.defineMemberName)
        MainWindow.setTabOrder(self.defineMemberName, self.defineNodeI)
        MainWindow.setTabOrder(self.defineNodeI, self.defineNodeJ)
        MainWindow.setTabOrder(self.defineNodeJ, self.addMemberButton)
        MainWindow.setTabOrder(self.addMemberButton, self.scrollArea_2)
        MainWindow.setTabOrder(self.scrollArea_2, self.editMemberName)
        MainWindow.setTabOrder(self.editMemberName, self.editNodeI)
        MainWindow.setTabOrder(self.editNodeI, self.editNodeJ)
        MainWindow.setTabOrder(self.editNodeJ, self.updateMemberButton)
        MainWindow.setTabOrder(self.updateMemberButton,
                               self.deleteMemberButton)
        MainWindow.setTabOrder(self.deleteMemberButton, self.tabs)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.defineNodeNameLabel.setText(_translate("MainWindow", "Node Name"))
        self.defineNodeZLabel.setText(_translate("MainWindow", "Global z (m)"))
        self.defineNodeYLabel.setText(_translate("MainWindow", "Global y (m)"))
        self.defineNodeXLabel.setText(_translate("MainWindow", "Global x (m)"))
        self.addNodeButton.setText(_translate("MainWindow", "Add Node"))
        self.label.setText(
            _translate(
                "MainWindow",
                "<html><head/><body><p>All function operations are the same.</p><p>For multiplication use * and ** for exponentials.</p><p>Angles are in radians.</p><p>Visit <a href=\"https://docs.sympy.org/latest/modules/functions/elementary.html\"><span style=\" text-decoration: underline; color:#000000;\">SymPy Elementary Functions</span></a> for a list of mathematical functions.</p></body></html>"
            ))
        self.defineNodeLabel.setText(_translate("MainWindow", "Define Nodes"))
        self.editNodeLabel.setText(_translate("MainWindow", "Edit Nodes"))
        self.editNodeName.setText(
            _translate("MainWindow", "Add node to get started"))
        self.updateNodeButton.setText(_translate("MainWindow", "Update"))
        self.deleteNodeButton.setText(_translate("MainWindow", "Delete"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1Node),
                             _translate("MainWindow", "Tab 1"))
        self.editMemberLabel.setText(_translate("MainWindow", "Edit Members"))
        self.updateMemberButton.setText(_translate("MainWindow", "Update"))
        self.editMemberName.setText(
            _translate("MainWindow", "Add member to get started"))
        self.deleteMemberButton.setText(_translate("MainWindow", "Delete"))
        self.defineMemberNameLabel.setText(
            _translate("MainWindow", "Member Name"))
        self.defineNodeJLabel.setText(_translate("MainWindow", "Node J"))
        self.addMemberButton.setText(_translate("MainWindow", "Add Member"))
        self.defineNodeILabel.setText(_translate("MainWindow", "Node I"))
        self.defineMemberLabel.setText(
            _translate("MainWindow", "Define Members"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2Member),
                             _translate("MainWindow", "Page"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
