name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prek:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: j178/prek-action@v2
